spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/depdb
    password: codezmr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
logging:
  file:
    name: app.log
    
# tools i used to convert properties to yml: http://mageddo.com/tools/yaml-converter